from dataclasses import dataclass
from enum import Enum

@dataclass
class TypeData:
    name : str
    symbol : str

class CardType(Enum):
    ARTIFACT     = TypeData(name='artifact',    symbol='A')
    CREATURE     = TypeData(name='creature',    symbol='C')
    LAND         = TypeData(name='land',        symbol='L')
    INSTANT      = TypeData(name='instant',     symbol='I')
    SORCERY      = TypeData(name='sorcery',     symbol='S')
    ENCHANTEMENT = TypeData(name='enchantment', symbol='E')
    BATTLE       = TypeData(name='battle',      symbol='B')
    KINDRED      = TypeData(name='kindred',     symbol='K')
    PLANESWALKER = TypeData(name='planeswalker',symbol='P')
    LEGENDARY    = TypeData(name='legendary'   ,symbol='LGD')
    SNOW         = TypeData(name='snow'        ,symbol='SNW')

    PLAINS       = TypeData(name='plains', symbol='PLAINS')
    ISLAND       = TypeData(name='island', symbol='ISLAND')
    SWAMP        = TypeData(name='swamp' , symbol='SWAMP')
    MOUNTAIN     = TypeData(name='mountain', symbol='MOUNTAIN')
    FOREST       = TypeData(name='forest', symbol='FOREST')
    DESERT       = TypeData(name='desert', symbol='DESERT')

    EQUIPMENT    = TypeData(name='equipment'  ,symbol='EQUIPMENT')
    VEHICLE      = TypeData(name='vehicle'  ,symbol='VEHICLE')
    
    AURA         = TypeData(name='aura'  ,symbol='AURA')
    SAGA         = TypeData(name='saga'  ,symbol='SAGA')
    CARTOUCHE    = TypeData(name='cartouche'  ,symbol='CARTOUCHE')
    
    SIEGE        = TypeData(name='siege'  ,symbol='SIEGE')
    
    ELSPETH      = TypeData(name='elspeth'  ,symbol='ELSPETH')
    JACE         = TypeData(name='jace'  ,symbol='JACE')
    LILIANA      = TypeData(name='liliana'  ,symbol='LILIANA')
    CHANDRA      = TypeData(name='chandra'  ,symbol='CHANDRA')
    VIVIEN       = TypeData(name='vivien'  ,symbol='VIVIEN')
    TEFERI       = TypeData(name='teferi'  ,symbol='TEFERI')
    KAITO        = TypeData(name='kaito'  ,symbol='KAITO')
    NIXILIS      = TypeData(name='nixilis'  ,symbol='NIXILIS')
    XENAGOS      = TypeData(name='xenagos'  ,symbol='XENAGOS')
    AJANI        = TypeData(name='ajani'  ,symbol='AJANI')
    KAYA         = TypeData(name='kaya'  ,symbol='KAYA')
    SAHEELI      = TypeData(name='saheeli'  ,symbol='SAHEELI')
    VRASKA       = TypeData(name='vraska'  ,symbol='VRASKA')
    KIORA        = TypeData(name='kiora'  ,symbol='KIORA')
    KARN         = TypeData(name='karn'  ,symbol='KARN')
    UGIN         = TypeData(name='ugin'  ,symbol='UGIN')
    
    HUMAN        = TypeData(name='human'       ,symbol='HUMAN')
    KNIGHT       = TypeData(name='knight'      ,symbol='KNIGHT')
    KOR          = TypeData(name='kor'         ,symbol='KOR')
    CLERIC       = TypeData(name='cleric'      ,symbol='CLERIC')
    SOLDIER      = TypeData(name='soldier'     ,symbol='SOLDIER')
    DWARF        = TypeData(name='dwarf'       ,symbol='DWARF')
    ARTIFICER    = TypeData(name='artificer'  ,symbol='ARTIFICER')
    SPIRIT       = TypeData(name='spirit'  ,symbol='SPIRIT')
    WARRIOR      = TypeData(name='warrior'  ,symbol='WARRIOR')
    VAMPIRE      = TypeData(name='vampire'  ,symbol='VAMPIRE')
    CAT          = TypeData(name='cat'  ,symbol='CAT')
    DEMIGOD      = TypeData(name='demigod'  ,symbol='DEMIGOD')
    PHYREXIAN    = TypeData(name='phyrexian'  ,symbol='PHYREXIAN')
    BIRD         = TypeData(name='bird'  ,symbol='BIRD')
    ROGUE        = TypeData(name='rogue'  ,symbol='ROGUE')
    ANGEL        = TypeData(name='angel'  ,symbol='ANGEL')
    MONK         = TypeData(name='monk'  ,symbol='MONK')
    WIZARD       = TypeData(name='wizard'  ,symbol='WIZARD')
    ELF          = TypeData(name='elf'  ,symbol='ELF')
    DRUID        = TypeData(name='druid'  ,symbol='DRUID')
    HORROR       = TypeData(name='horror'  ,symbol='HORROR')
    GOLEM        = TypeData(name='golem'  ,symbol='GOLEM')
    CONSTRUCT    = TypeData(name='construct'  ,symbol='CONSTRUCT')
    ELEMENTAL    = TypeData(name='elemental'  ,symbol='ELEMENTAL')
    DRAGON       = TypeData(name='dragon'  ,symbol='DRAGON')
    SALAMANDER   = TypeData(name='salamander'  ,symbol='SALAMANDER')
    DRAKE        = TypeData(name='drake'  ,symbol='DRAKE')
    SIREN        = TypeData(name='siren'  ,symbol='SIREN')
    PIRATE       = TypeData(name='pirate'  ,symbol='PIRATE')
    MERFOLK      = TypeData(name='merfolk'  ,symbol='MERFOLK')
    FAERIE       = TypeData(name='faerie'  ,symbol='FAERIE')
    NINJA        = TypeData(name='ninja'  ,symbol='NINJA')
    WEREWOLF     = TypeData(name='werewolf'  ,symbol='WEREWOLF')
    NAGA         = TypeData(name='naga'  ,symbol='NAGA')
    SHARK        = TypeData(name='shark'  ,symbol='SHARK')
    VEDALKEN     = TypeData(name='vedalken'  ,symbol='VEDALKEN')
    DETECTIVE    = TypeData(name='detective'  ,symbol='DETECTIVE')
    OCTOPUS      = TypeData(name='octopus'  ,symbol='OCTOPUS')
    MOONFOLK     = TypeData(name='moonfolk'  ,symbol='MOONFOLK')
    SHAPESHIFTER = TypeData(name='shapeshifter'  ,symbol='SHAPESHIFTER')
    SPHINX       = TypeData(name='sphinx'  ,symbol='SPHINX')
    GIANT        = TypeData(name='giant'  ,symbol='GIANT')
    TURTLE       = TypeData(name='turtle'  ,symbol='TURTLE')
    SERPENT      = TypeData(name='serpent'  ,symbol='SERPENT')
    ZOMBIE       = TypeData(name='zombie'  ,symbol='ZOMBIE')
    JACKAL       = TypeData(name='jackal'  ,symbol='JACKAL')
    SKELETON     = TypeData(name='skeleton'  ,symbol='SKELETON')
    SHADE        = TypeData(name='shade'  ,symbol='SHADE')
    ALLY         = TypeData(name='ally'  ,symbol='ALLY')
    NIGHTMARE    = TypeData(name='nightmare'  ,symbol='NIGHTMARE')
    PRAETOR      = TypeData(name='praetor'  ,symbol='PRAETOR')
    WARLOCK      = TypeData(name='warlock'  ,symbol='WARLOCK')
    RAT          = TypeData(name='rat'  ,symbol='RAT')
    SHAMAN       = TypeData(name='shaman'  ,symbol='SHAMAN')
    DINOSAUR     = TypeData(name='dinosaur'  ,symbol='DINOSAUR')
    AETHERBORN   = TypeData(name='aetherborn'  ,symbol='AETHERBORN')
    TIEFLING     = TypeData(name='tiefling'  ,symbol='TIEFLING')
    BEAST        = TypeData(name='beast'  ,symbol='BEAST')
    FISH         = TypeData(name='fish'  ,symbol='FISH')
    WURM         = TypeData(name='wurm'  ,symbol='WURM')
    GOBLIN       = TypeData(name='goblin'  ,symbol='GOBLIN')
    RABBIT       = TypeData(name='rabbit'  ,symbol='RABBIT')
    SAMURAI      = TypeData(name='samurai'  ,symbol='SAMURAI')
    KAVU         = TypeData(name='kavu'  ,symbol='KAVU')
    DOG          = TypeData(name='dog'  ,symbol='DOG')
    MINOTAUR     = TypeData(name='minotaur'  ,symbol='MINOTAUR')
    SCOUT        = TypeData(name='scout'  ,symbol='SCOUT')
    PHOENIX      = TypeData(name='phoenix'  ,symbol='PHOENIX')
    BERSERKER    = TypeData(name='berserker'  ,symbol='BERSERKER')
    ARCHER       = TypeData(name='archer'  ,symbol='ARCHER')
    ELDER        = TypeData(name='elder'  ,symbol='ELDER')
    DEVIL        = TypeData(name='devil'  ,symbol='DEVIL')
    PLANT        = TypeData(name='plant'  ,symbol='PLANT')
    FUNGUS       = TypeData(name='fungus'  ,symbol='FUNGUS')
    SNAKE        = TypeData(name='snake'  ,symbol='SNAKE')
    SATYR        = TypeData(name='satyr'  ,symbol='SATYR')
    OOZE         = TypeData(name='ooze'  ,symbol='OOZE')
    CENTAUR      = TypeData(name='centaur'  ,symbol='CENTAUR')
    APE          = TypeData(name='ape'  ,symbol='APE')
    TREEFOLK     = TypeData(name='treefolk'  ,symbol='TREEFOLK')
    DRYAD        = TypeData(name='dryad'  ,symbol='DRYAD')
    BEAR         = TypeData(name='bear'  ,symbol='BEAR')
    WOLF         = TypeData(name='wolf'  ,symbol='WOLF')
    HYDRA        = TypeData(name='hydra'  ,symbol='HYDRA')
    TROLL        = TypeData(name='troll'  ,symbol='TROLL')
    RHINO        = TypeData(name='rhino'  ,symbol='RHINO')
    PILOT        = TypeData(name='pilot'  ,symbol='PILOT')
    DEMON        = TypeData(name='demon'  ,symbol='DEMON')
    KRAKEN       = TypeData(name='kraken'  ,symbol='KRAKEN')
    NOBLE        = TypeData(name='noble'  ,symbol='NOBLE')
    OGRE         = TypeData(name='ogre'  ,symbol='OGRE')
    MERCENARY    = TypeData(name='mercenary'  ,symbol='MERCENARY')
    WEIRD        = TypeData(name='weird'  ,symbol='WEIRD')
    SQUIRREL     = TypeData(name='squirrel'  ,symbol='SQUIRREL')
    SPIDER       = TypeData(name='spider'  ,symbol='SPIDER')
    FROG         = TypeData(name='frog'  ,symbol='FROG')
    MOUNT        = TypeData(name='mount'  ,symbol='MOUNT')
    HALFLING     = TypeData(name='halfling'  ,symbol='HALFLING')
    JELLYFISH    = TypeData(name='jellyfish'  ,symbol='JELLYFISH')
    ELK          = TypeData(name='elk'  ,symbol='ELK')
    THOPTER      = TypeData(name='thopter'  ,symbol='THOPTER')
    MYR          = TypeData(name='myr'  ,symbol='MYR')

SYMBOL_TO_TYPE = {c.value.symbol:c for c in CardType}
NAME_TO_TYPE   = {c.value.name:c   for c in CardType}

def get_type(card_type_name:str)->CardType:
    """Return a card type from its name of its symbol."""

    try_name = NAME_TO_TYPE.get(card_type_name.lower(), None)
    try_symbol = SYMBOL_TO_TYPE.get(card_type_name.capitalize(), None)

    if try_name : return try_name
    if try_symbol : return try_symbol

    raise ValueError(
        f'Invalid card type name, got {card_type_name}, expected a symbol' \
        # f'({list(SYMBOL_TO_TYPE.keys())}) or a name '\
        # f'({list(NAME_TO_TYPE.keys())}).'
    )

def get_type_list(card_type_names:list[str])->list[CardType]:
    return [get_type(t) for t in card_type_names]